/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dce1ff",
        "secondary": "#b6c4ff",
        "on-tertiary": "#690007",
        "surface": "#111319",
        "tertiary": "#ffb4ac",
        "background": "#111319",
        "on-secondary-fixed": "#00164e",
        "surface-container": "#1d2025",
        "surface-variant": "#33353b",
        "surface-card": "#131722",
        "primary-fixed-dim": "#e9c176",
        "surface-dark": "#07090e",
        "inverse-primary": "#775a19",
        "secondary-fixed-dim": "#b6c4ff",
        "on-surface": "#e2e2ea",
        "secondary-container": "#264191",
        "primary-fixed": "#ffdea5",
        "primary": "#e9c176",
        "primary-container": "#c5a059",
        "on-surface-variant": "#d1c5b4",
        "inverse-surface": "#e2e2ea",
        "on-primary-container": "#4e3700",
        "brand-navy-light": "#1e3a8a",
        "on-background": "#e2e2ea",
        "tertiary-fixed": "#ffdad6",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "text-muted": "#94a3b8",
        "on-primary-fixed-variant": "#5d4201",
        "brand-crimson": "#991B1B",
        "brand-gold-bright": "#E5C158",
        "outline-variant": "#4e4639",
        "surface-container-highest": "#33353b",
        "surface-container-high": "#282a30",
        "brand-gold": "#C5A059",
        "tertiary-fixed-dim": "#ffb4ac",
        "border-dark": "#232d42",
        "surface-tint": "#e9c176",
        "on-tertiary-fixed-variant": "#8e1214",
        "on-tertiary-fixed": "#410002",
        "on-primary": "#412d00",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#264191",
        "on-secondary": "#05297a",
        "surface-container-lowest": "#0c0e13",
        "surface-card-subtle": "#1c2233",
        "on-error": "#690005",
        "surface-dim": "#111319",
        "surface-bright": "#37393f",
        "outline": "#9a8f80",
        "on-tertiary-container": "#7d000a",
        "brand-navy": "#0f172a",
        "on-primary-fixed": "#261900",
        "tertiary-container": "#ff7f74",
        "on-secondary-container": "#9db2ff",
        "surface-container-low": "#191c21",
        "inverse-on-surface": "#2e3036"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-xl": "1.75rem",
        "margin": "1.25rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        "gutter": "0.625rem",
        "space-md": "0.875rem"
      },
      fontFamily: {
        sans: ["'Poppins'", "sans-serif"],
        "headline-sm": ["'Poppins'", "sans-serif"],
        "display-hero": ["'Poppins'", "sans-serif"],
        "body-md": ["'Poppins'", "sans-serif"],
        "headline-lg": ["'Poppins'", "sans-serif"],
        "headline-md": ["'Poppins'", "sans-serif"],
        "label-md": ["'Poppins'", "sans-serif"],
        "body-sm": ["'Poppins'", "sans-serif"],
        "label-sm": ["'Poppins'", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["14px", { "lineHeight": "18px", "fontWeight": "700" }],
        "display-hero": ["34px", { "lineHeight": "38px", "fontWeight": "800" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "headline-lg": ["19px", { "lineHeight": "24px", "fontWeight": "700" }],
        "headline-md": ["17px", { "lineHeight": "22px", "fontWeight": "700" }],
        "label-md": ["11px", { "lineHeight": "14px", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "12px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
